// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlDgNzOW05QIwUKPxY4_2C0ppipL3GVX4',
    appId: '1:896506768903:web:e773de378336bc944d44a2',
    messagingSenderId: '896506768903',
    projectId: 'efoc-fcf44',
    authDomain: 'efoc-fcf44.firebaseapp.com',
    storageBucket: 'efoc-fcf44.firebasestorage.app',
    measurementId: 'G-KZSG799F73',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCvdrop7PGFySMKuDp-7-6iNuVbPYxi3Q',
    appId: '1:896506768903:android:0b221a79182ce7b84d44a2',
    messagingSenderId: '896506768903',
    projectId: 'efoc-fcf44',
    storageBucket: 'efoc-fcf44.firebasestorage.app',
  );
}
